development:
  secret_key_base: a123ee005cdfaaf93175ddcd50ea269cca854c4414f5f1268c44127cc437d571b09005408c77e0edac2113e778ab77d3be5ca0da0bb845fc94cc5154edb92d91
  client_url: http://localhost:4200
  moip_token: FTREMVPGZQ98VRR5UNRTRAORPBBHQK4U
  moip_secret: MYXMEEOEH81PVW8G9C347QECNNG0JZLKKTRXVPHU
  moip_environment: sandbox

test:
  secret_key_base: 914d0cf0163dd5ef183d7f274f7e1c6d311746ac397bed084b6cf9d3987cd8a2c38968807442ae2ef5fee34e9af957fe76d425bf78e67e5e5898a3aecf96e94c
  client_url: http://localhost:4200
  moip_token: FTREMVPGZQ98VRR5UNRTRAORPBBHQK4U
  moip_secret: MYXMEEOEH81PVW8G9C347QECNNG0JZLKKTRXVPHU
  moip_environment: sandbox

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  client_url: http://localhost:4200
  moip_token: your_production_token
  moip_secret: your_production_secret
  moip_environment: production
